# Generated by Django 5.2.13 on 2026-05-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FailedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.JSONField(help_text="收件人列表，如 ['user@example.com']")),
                ('subject_template', models.CharField(max_length=200)),
                ('body_text_template', models.CharField(max_length=200)),
                ('body_html_template', models.CharField(max_length=200)),
                ('context', models.JSONField(help_text='渲染模板用的 context dict')),
                ('last_error', models.TextField(help_text='最后一次失败的 exception traceback')),
                ('attempts', models.PositiveIntegerField(help_text='累计尝试次数（含 Celery 重试）')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='手动重发成功后置 now()（v0.1 暂不实现自动重发，预留字段）', null=True)),
            ],
            options={
                'db_table': 'notifications_failed_emails',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['resolved_at', '-created_at'], name='notificatio_resolve_a5f47b_idx')],
            },
        ),
    ]
