# Generated by Django 5.2.13 on 2026-05-12 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='failedemail',
            options={'ordering': ['-created_at'], 'verbose_name': '失败邮件', 'verbose_name_plural': '失败邮件队列'},
        ),
    ]
