# Generated by Django 5.2.13 on 2026-05-05 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(unique=True)),
                ('type', models.CharField(choices=[('skill', 'Skill')], default='skill', max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('tags', models.JSONField(default=list)),
                ('latest_version_id', models.PositiveIntegerField(blank=True, null=True)),
                ('install_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'submit_skills',
            },
        ),
        migrations.CreateModel(
            name='SkillVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_no', models.PositiveIntegerField()),
                ('file_path', models.CharField(max_length=500)),
                ('sha256', models.CharField(max_length=64)),
                ('readme', models.TextField()),
                ('status', models.CharField(choices=[('pending_machine', '待机审'), ('pending_review', '待人审'), ('changes_requested', '需修改'), ('published', '已发布'), ('rejected', '已拒绝'), ('cancelled', '已取消')], db_index=True, default='pending_machine', max_length=30)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('machine_review_result', models.JSONField(blank=True, null=True)),
                ('violations', models.JSONField(blank=True, null=True)),
                ('llm_review_result', models.JSONField(blank=True, null=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='submit.skill')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'submit_skill_versions',
                'indexes': [models.Index(fields=['skill', 'status', '-submitted_at'], name='sv_skill_status_submitted_at')],
                'unique_together': {('skill', 'version_no')},
            },
        ),
    ]
