# Generated by Django 5.2.13 on 2026-05-05 13:06

import django.db.models.deletion
from django.db import migrations, models


def add_in_flight_generated_column(apps, schema_editor):
    """MySQL only: add generated column + unique index for in-flight constraint."""
    if schema_editor.connection.vendor != "mysql":
        return
    schema_editor.execute(
        "ALTER TABLE submit_skill_versions "
        "ADD COLUMN in_flight_skill_id BIGINT "
        "GENERATED ALWAYS AS ("
        "CASE WHEN status IN ('pending_machine','pending_review','changes_requested') "
        "THEN skill_id END"
        ") STORED, "
        "ADD UNIQUE KEY uk_skill_inflight (in_flight_skill_id)"
    )


def remove_in_flight_generated_column(apps, schema_editor):
    """MySQL only: drop generated column + unique index."""
    if schema_editor.connection.vendor != "mysql":
        return
    schema_editor.execute(
        "ALTER TABLE submit_skill_versions "
        "DROP KEY uk_skill_inflight, "
        "DROP COLUMN in_flight_skill_id"
    )


class Migration(migrations.Migration):

    atomic = False  # raw DDL (ALTER TABLE) 不能在 mysql 事务内跑，Django 检测到 transaction 抛 TransactionManagementError

    dependencies = [
        ('submit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='latest_version_id',
        ),
        migrations.AddField(
            model_name='skill',
            name='latest_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='submit.skillversion'),
        ),
        migrations.AddField(
            model_name='skillversion',
            name='published_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        # WARNING: status list mirrors SkillVersion.NON_TERMINAL_STATUSES.
        # If a new non-terminal status is added, this generated column must be
        # updated via a new migration or the DB constraint will silently stop enforcing it.
        # MySQL-only: no-op on SQLite (TEST_USE_SQLITE=1).
        migrations.RunPython(
            add_in_flight_generated_column,
            reverse_code=remove_in_flight_generated_column,
        ),
    ]
