# Generated by Django 5.2.13 on 2026-05-09 02:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0002_skill_versioning'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('request_changes', 'Request changes'), ('cancel_by_author', 'Cancel by author'), ('auto_cancel_by_resubmit', 'Auto cancel (resubmit)')], max_length=32)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_actions', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_actions', to='submit.skillversion')),
            ],
            options={
                'db_table': 'submit_review_actions',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['version', '-created_at'], name='ra_version_created')],
            },
        ),
    ]
