# Generated by Django 5.2.13 on 2026-05-12 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0004_skills_fulltext_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewaction',
            options={'ordering': ('-created_at',), 'verbose_name': '审核操作历史', 'verbose_name_plural': '审核操作历史'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'Skill 项目', 'verbose_name_plural': 'Skill 项目'},
        ),
        migrations.AlterModelOptions(
            name='skillversion',
            options={'verbose_name': 'Skill 版本（待审 / 已发布）', 'verbose_name_plural': 'Skill 版本'},
        ),
    ]
