# Generated by Django 5.2.13 on 2026-05-16 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0006_skillversion_download_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingSkillVersion',
            fields=[
            ],
            options={
                'verbose_name': 'Skill 审核',
                'verbose_name_plural': 'Skill 审核',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('submit.skillversion',),
        ),
        migrations.AlterModelOptions(
            name='reviewaction',
            options={'ordering': ('-created_at',), 'verbose_name': '审核日志', 'verbose_name_plural': '审核日志'},
        ),
        migrations.AddField(
            model_name='skill',
            name='is_listed',
            field=models.BooleanField(db_index=True, default=True, help_text='是否在 catalog 公开侧露出。False=已下线（仅 owner/staff 详情可见，install 链接 404）。'),
        ),
        migrations.AlterField(
            model_name='reviewaction',
            name='action',
            field=models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('request_changes', 'Request changes'), ('cancel_by_author', 'Cancel by author'), ('auto_cancel_by_resubmit', 'Auto cancel (resubmit)'), ('delist', 'Delist'), ('relist', 'Relist'), ('rollback', 'Rollback')], max_length=32),
        ),
    ]
