# Generated by Django 5.2.13 on 2026-05-17 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0007_admin_skill_management'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillversion',
            name='is_available',
            field=models.BooleanField(db_index=True, default=True, help_text='是否对用户可见可装。False=已下线版本（catalog ?v= 与 install 链接 404）。与 skill 级 is_listed 正交：双闸门任一关都不可见。'),
        ),
        migrations.AlterField(
            model_name='reviewaction',
            name='action',
            field=models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('request_changes', 'Request changes'), ('cancel_by_author', 'Cancel by author'), ('auto_cancel_by_resubmit', 'Auto cancel (resubmit)'), ('delist', 'Delist'), ('relist', 'Relist'), ('rollback', 'Rollback'), ('disable_version', 'Disable version'), ('enable_version', 'Enable version')], max_length=32),
        ),
    ]
