# Generated by Django 5.2.13 on 2026-05-17 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0008_version_is_available'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_skills', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='description',
            field=models.CharField(max_length=200, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='install_count',
            field=models.PositiveIntegerField(default=0, verbose_name='安装次数'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='is_listed',
            field=models.BooleanField(db_index=True, default=True, help_text='是否在 catalog 公开侧露出。False=已下线（仅 owner/staff 详情可见，install 链接 404）。', verbose_name='上下线状态'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='latest_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='submit.skillversion', verbose_name='最新版本'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.SlugField(unique=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='tags',
            field=models.JSONField(default=list, verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='type',
            field=models.CharField(choices=[('skill', 'Skill')], default='skill', max_length=20, verbose_name='类型'),
        ),
    ]
