# Generated by Django 5.2.13 on 2026-05-17 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0009_alter_skill_created_at_alter_skill_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'Skill', 'verbose_name_plural': 'Skill 列表'},
        ),
    ]
