# Generated by Django 5.2.13 on 2026-05-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0010_alter_skill_verbose_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillversion',
            name='status',
            field=models.CharField(choices=[('pending_machine', '待机审'), ('pending_review', '待管理员审核'), ('changes_requested', '需修改'), ('published', '已发布'), ('rejected', '已拒绝'), ('cancelled', '已取消')], db_index=True, default='pending_machine', max_length=30),
        ),
    ]
